# Generated by Django 3.0.8 on 2020-07-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200721_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Игры', 'verbose_name_plural': 'игры'},
        ),
    ]
