# Generated by Django 3.0.8 on 2020-08-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200804_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
