# Generated by Django 3.0.8 on 2020-07-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200723_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categorys',
            new_name='category',
        ),
    ]
