# Generated by Django 3.0.8 on 2020-07-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200723_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_images', verbose_name='Изображение Игры'),
        ),
    ]
